# Generated by Django 6.0.2 on 2026-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kamera_adi', models.CharField(max_length=50)),
                ('ham_sayisi', models.IntegerField(default=0)),
                ('yari_olgun_sayisi', models.IntegerField(default=0)),
                ('olgun_sayisi', models.IntegerField(default=0)),
                ('ortalama_olgunluk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('analiz_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analiz_gecmisi',
                'ordering': ['-analiz_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='TomatoAnalysis',
        ),
    ]
